######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 14 14:43:44 2015
######################################################################
QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.hpp MW_Udp_Receiver.hpp
FORMS += MW_Udp_Receiver.ui
SOURCES += main.cpp MainWindow.cpp
